// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ApiEntityFramework.Data.Configurations;
using ApiEntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace ApiEntityFramework.Data;

public partial class eCommerceNetContext : DbContext
{
    public eCommerceNetContext(DbContextOptions<eCommerceNetContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CantidadProducto> CantidadProductos { get; set; }

    public virtual DbSet<Carrito> Carritos { get; set; }

    public virtual DbSet<Direccion> Direccions { get; set; }

    public virtual DbSet<MetodoPago> MetodoPagos { get; set; }

    public virtual DbSet<OrdenDetalle> OrdenDetalles { get; set; }

    public virtual DbSet<OrdenPago> OrdenPagos { get; set; }

    public virtual DbSet<Producto> Productos { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.CantidadProductoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CarritoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DireccionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.MetodoPagoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.OrdenDetalleConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.OrdenPagoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UsuarioConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
