// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ApiEntityFramework.Data;
using ApiEntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ApiEntityFramework.Data.Configurations
{
    public partial class OrdenDetalleConfiguration : IEntityTypeConfiguration<OrdenDetalle>
    {
        public void Configure(EntityTypeBuilder<OrdenDetalle> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_ordenDetalle_1");

            entity.ToTable("ordenDetalle");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.IdOrdenPago).HasColumnName("idOrdenPago");
            entity.Property(e => e.IdProducto).HasColumnName("idProducto");
            entity.Property(e => e.PrecioProducto)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("precioProducto");

            entity.HasOne(d => d.IdOrdenPagoNavigation).WithMany(p => p.OrdenDetalles)
            .HasForeignKey(d => d.IdOrdenPago)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ordenDetalle_ordenPago1");

            entity.HasOne(d => d.IdProductoNavigation).WithMany(p => p.OrdenDetalles)
            .HasForeignKey(d => d.IdProducto)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ordenDetalle_producto");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrdenDetalle> entity);
    }
}
