// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ApiEntityFramework.Data;
using ApiEntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ApiEntityFramework.Data.Configurations
{
    public partial class OrdenPagoConfiguration : IEntityTypeConfiguration<OrdenPago>
    {
        public void Configure(EntityTypeBuilder<OrdenPago> entity)
        {
            entity.ToTable("ordenPago");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Fecha)
            .HasColumnType("datetime")
            .HasColumnName("fecha");
            entity.Property(e => e.IdDireccion).HasColumnName("idDireccion");
            entity.Property(e => e.IdMetodo).HasColumnName("idMetodo");
            entity.Property(e => e.IdUsuario).HasColumnName("idUsuario");
            entity.Property(e => e.Total)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("total");

            entity.HasOne(d => d.IdDireccionNavigation).WithMany(p => p.OrdenPagos)
            .HasForeignKey(d => d.IdDireccion)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ordenPago_direccion");

            entity.HasOne(d => d.IdMetodoNavigation).WithMany(p => p.OrdenPagos)
            .HasForeignKey(d => d.IdMetodo)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ordenPago_metodoPago");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.OrdenPagos)
            .HasForeignKey(d => d.IdUsuario)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ordenPago_usuario");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrdenPago> entity);
    }
}
