// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ApiEntityFramework.Data;
using ApiEntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ApiEntityFramework.Data.Configurations
{
    public partial class UsuarioConfiguration : IEntityTypeConfiguration<Usuario>
    {
        public void Configure(EntityTypeBuilder<Usuario> entity)
        {
            entity.ToTable("usuario");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Email)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("email");
            entity.Property(e => e.Fecha)
            .HasColumnType("datetime")
            .HasColumnName("fecha");
            entity.Property(e => e.Password)
            .IsRequired()
            .HasMaxLength(8)
            .IsUnicode(false)
            .HasColumnName("password");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Usuario> entity);
    }
}
