// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiEntityFramework.Models;

public partial class MetodoPago
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<OrdenPago> OrdenPagos { get; set; } = new List<OrdenPago>();
}